# Kanagawa Lotus (Light) - Inspirado en rebelot/kanagawa.nvim
# Base: fujiWhite (#DCD7BA)

background #DCD7BA
foreground #454152

cursor #454152
selection_foreground #454152
selection_background #C3BAB8

# Paleta Normal (Colores 0-7)
color0 #DCD7BA
color1 #C34043
color2 #7FB472
color3 #E6C384
color4 #658594
color5 #9A7AA0
color6 #8FE4E2
color7 #454152

# Paleta Brillante (Colores 8-15)
color8 #8B8779
color9 #E87979
color10 #A8CC8C
color11 #EBA435
color12 #7E9CD8
color13 #C8C093
color14 #95E6CB
color15 #363646
