# kanagawa-lotus.conf
# Sabor "Lotus" (Claro)

foreground            #545464
background            #F2ECBC
selection_background  #9FB5C9
selection_foreground  #545464
cursor                #43436C
cursor_text_color     #F2ECBC

# Colores ANSI (Normal)
color0                #1F1F28
color1                #C84053
color2                #6F894E
color3                #77713F
color4                #4D699B
color5                #B35B79
color6                #597B75
color7                #727169

# Colores ANSI (Brillantes)
color8                #54546D
color9                #E82424
color10               #98BB6C
color11               #E6C384
color12               #7E9CD8
color13               #D27E99
color14               #7AA89F
color15               #545464
