# Tema OldWorld (Modificación Final - Selección Alto Contraste INVERSO)

# Fondo oscuro
background #000000
# Letras al máximo de claridad (Blanco Puro - OK)
foreground #FFFFFF

# Cursor blanco
cursor #FFFFFF

# SELECCIÓN MODIFICADA:
# Fondo de selección NEGRO PURO (o muy oscuro).
selection_background #000000 
# Texto seleccionado ROJO FUEGO/BRILLANTE (#FF0000) para que destaque sobre el fondo.
selection_foreground #FF0000

# Paleta Normal (Colores 0-7)
color0 #000000
color1 #EA83A5
color2 #90B99F
color3 #E6B99D
color4 #85B5BA
color5 #92A2D5
color6 #85B5BA
# Color 7 (blanco normal) AL MÁXIMO DE CLARIDAD
color7 #FFFFFF

# Paleta Brillante (Colores 8-15)
color8 #4D4D4D
color9 #EA83A5
color10 #90B99F
color11 #F5A191
color12 #85B5BA
color13 #92A2D5
color14 #85B5BA
# Blanco brillante
color15 #FFFFFF
